# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
INHERIT: mkdocs/base.yml  # use the shared AutoRA configuration by default

site_name: XRAITest
repo_url: 'https://github.com/PsyRes-Osnabrueck-University/website_test.git'

nav:
- Home: 'BasicUsage.ipynb'
# - Examples:
#   - Basic Usage: 'BasicUsage.ipynb'
