# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
INHERIT: mkdocs/base.yml  # use the shared AutoRA configuration by default

site_name: AutoRA g-1
repo_url: 'https://github.com/MoAljam/autora-theorist-g-1'

nav:
- Home: 'index.md'
- Examples:
  - Basic Usage: 'Basic Usage.ipynb'
